"""add unique constraint to planned workouts

Revision ID: 1a3d9ddc591f
Revises: d930bf35ff1a
Create Date: 2026-08-31 13:31:19.732211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a3d9ddc591f'
down_revision: Union[str, Sequence[str], None] = 'd930bf35ff1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_planned_workout_week_date', 'planned_workouts', ['week_id', 'scheduled_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_planned_workout_week_date', 'planned_workouts', type_='unique')
    # ### end Alembic commands ###
