"""add chunk_index

Revision ID: 92f0e5ad34f2
Revises: 5588b09fe211
Create Date: 2026-09-28 17:19:27.708483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92f0e5ad34f2'
down_revision: Union[str, Sequence[str], None] = '5588b09fe211'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_chunks', sa.Column('chunk_index', sa.Integer(), nullable=False))
    op.create_unique_constraint('uq_knowledge_source_chunk', 'knowledge_chunks', ['source', 'chunk_index'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_knowledge_source_chunk', 'knowledge_chunks', type_='unique')
    op.drop_column('knowledge_chunks', 'chunk_index')
    # ### end Alembic commands ###
