"""create training domain

Revision ID: d930bf35ff1a
Revises: 
Create Date: 2026-08-27 22:07:33.550940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd930bf35ff1a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athletes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_athletes_external_id'), 'athletes', ['external_id'], unique=True)
    op.create_table('training_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('duration_weeks', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_plans_athlete_id'), 'training_plans', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_training_plans_status'), 'training_plans', ['status'], unique=False)
    op.create_table('training_plan_weeks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_plan_id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('focus', sa.JSON(), nullable=False),
    sa.Column('intensity', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['training_plan_id'], ['training_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_plan_weeks_status'), 'training_plan_weeks', ['status'], unique=False)
    op.create_index(op.f('ix_training_plan_weeks_training_plan_id'), 'training_plan_weeks', ['training_plan_id'], unique=False)
    op.create_table('planned_workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('workout_type', sa.String(length=50), nullable=False),
    sa.Column('workout_name', sa.String(length=255), nullable=False),
    sa.Column('workout_data', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('garmin_workout_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['week_id'], ['training_plan_weeks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planned_workouts_scheduled_date'), 'planned_workouts', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_planned_workouts_status'), 'planned_workouts', ['status'], unique=False)
    op.create_index(op.f('ix_planned_workouts_week_id'), 'planned_workouts', ['week_id'], unique=False)
    op.create_table('training_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('training_plan_id', sa.Integer(), nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=True),
    sa.Column('workout_id', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['training_plan_id'], ['training_plans.id'], ),
    sa.ForeignKeyConstraint(['week_id'], ['training_plan_weeks.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['planned_workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_feedback_athlete_id'), 'training_feedback', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_training_feedback_training_plan_id'), 'training_feedback', ['training_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_feedback_training_plan_id'), table_name='training_feedback')
    op.drop_index(op.f('ix_training_feedback_athlete_id'), table_name='training_feedback')
    op.drop_table('training_feedback')
    op.drop_index(op.f('ix_planned_workouts_week_id'), table_name='planned_workouts')
    op.drop_index(op.f('ix_planned_workouts_status'), table_name='planned_workouts')
    op.drop_index(op.f('ix_planned_workouts_scheduled_date'), table_name='planned_workouts')
    op.drop_table('planned_workouts')
    op.drop_index(op.f('ix_training_plan_weeks_training_plan_id'), table_name='training_plan_weeks')
    op.drop_index(op.f('ix_training_plan_weeks_status'), table_name='training_plan_weeks')
    op.drop_table('training_plan_weeks')
    op.drop_index(op.f('ix_training_plans_status'), table_name='training_plans')
    op.drop_index(op.f('ix_training_plans_athlete_id'), table_name='training_plans')
    op.drop_table('training_plans')
    op.drop_index(op.f('ix_athletes_external_id'), table_name='athletes')
    op.drop_table('athletes')
    # ### end Alembic commands ###
